### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Ali-Alzyoud** [dalihub/dali-demo#1]
When try to build latest with latest Dali- libraries, I get following compilation error:

```
dali-demo/examples/item-view/item-view-example.cpp:200:12: error: ‘class Dali::Window’ has no member named ‘KeyEventSignal’; did you mean ‘ResizedSignal’?
     window.KeyEventSignal().Connect(this, &ItemViewExample::OnKeyEvent);

dali-demo/examples/item-view/item-view-example.cpp:203:40: error: conversion from ‘Dali::Window::WindowSize {aka Dali::Uint16Pair}’ to non-scalar type ‘Dali::Vector2’ requested
     Vector2 windowSize = window.GetSize();

```

**Comment by id213sin** [comment]
`dali-demo/examples/item-view/item-view-example.cpp:200:12: error: ‘class Dali::Window’ has no member named ‘KeyEventSignal’; did you mean ‘ResizedSignal’?`
`window.KeyEventSignal().Connect(this, &ItemViewExample::OnKeyEvent);`

You can check your code for Window::KeyEventSignal() in the file:
dali-adaptor/dali/public-api/adaptor-framework/window.cpp: 336
dali-adaptor/dali/public-api/adaptor-framework/window.h: 658

**Comment by Ali-Alzyoud** [comment]
@id213sin  Thank you, it seems I have old header somewhere hidden in my system
