### ISSUE TITLE
Dali TextEditor outside boundary 

### ISSUE THREAD

**Issue by Ali-Alzyoud** [dalihub/dali-demo#2]
Dali Text Editor is drawing outside of its boundaries

![Screenshot from 2021-05-29 20-57-31](https://user-images.githubusercontent.com/8048094/120080346-1d6f8100-c0c1-11eb-9726-56ce438d73f7.png)

**Comment by wonrst** [comment]
Hello @Ali-Alzyoud ,

This issue from latest patch (dali-toolkit).
(Remove DevelColorVisual::Property::RENDER_IF_TRANSPARENT)
(3c6245ad032678461d6df519db63240016f43ed7)

I reported this issue to Heeyong Song.
Thanks :)

**Comment by wonrst** [comment]
Issue resolved : 
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-core/+/258978/

**Comment by Ali-Alzyoud** [comment]
It is fixed, thank you
